---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: odf-storagecluster-cephblockpool
  namespace: openshift-storage
spec:
  deviceClass: "dc-standard"
  enableRBDStats: true
  failureDomain: rack
  erasureCoded:
    codingChunks: 0
    dataChunks: 0
  replicated:
    requiredSafeReplicaSize: false
    size: 2
    targetSizeRatio: 0.95



