---
- name: General vars for VMs
  set_fact:
    vm_name: "{{ custom_vm_name }}-{{ ocp_cluster_name }}"


- name: Destroy storage pools
  command: virsh pool-destroy {{ vm_name }}-odf
  ignore_errors: yes


- name: Check to see if ODF path is valid
  ansible.builtin.stat:
    path: "{{ odf_disk_path }}"
  register: p

- name: Remove ODF storage directories
  shell: |
    rm -rf {{ odf_disk_path }}/* &> /dev/null
  when: p.stat.isdir is defined and p.stat.isdir