---
- name: Zap none OS disks
  shell: |
    oc debug node/{{ custom_vm_name }} -- chroot /host sgdisk --zap-all --clear {{ item }}
  loop:
    - "{{ data_disks.standard.disk_path }}"
    - "{{ data_disks.fast.disk_path }}"
  throttle: 1


- name: Wipe none OS disks
  shell: |
    oc debug node/{{ custom_vm_name }} -- chroot /host wipefs -a {{ item }}
  loop:
    - "{{ data_disks.standard.disk_path }}"
    - "{{ data_disks.fast.disk_path }}"
  throttle: 1


- name: Update device partition table
  shell: |
    oc debug node/{{ custom_vm_name }} -- chroot /host kpartx -f -v {{ item }}
  loop:
    - "{{ data_disks.standard.disk_path }}"
    - "{{ data_disks.fast.disk_path }}"
  throttle: 1