apiVersion: v1
baseDomain: {{ base_domain }}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: {{ groups['worker'] | length }}
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: {{ groups['control'] | length }}
metadata:
  name: {{ ocp_cluster_name }}
networking:
  machineNetwork:
  - cidr: 192.168.0.0/8
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: {{ ocp_network_type}}
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
additionalTrustBundle: |
{{ additional_trust_bundle | indent(width=2, first=true) }}
pullSecret: '{{ pull_secret | trim  }}'
sshKey: '{{ rhcos_ssh_pub_key }}'