---



- name: Destroy VMS
  command: virsh destroy {{ item }}
  ignore_errors: yes
  loop:
    - bootstrap
    - control1
    - control2
    - control3
    - worker1
    - worker2
    - worker3


- name: Undefine VMS
  command: virsh undefine {{ item }}
  ignore_errors: yes
  loop:
    - bootstrap
    - control1
    - control2
    - control3
    - worker1
    - worker2
    - worker3
- name: Undefine VMS
  command: virsh undefine {{ item }}
  ignore_errors: yes
  loop:
    - bootstrap
    - control1
    - control2
    - control3
    - worker1
    - worker2
    - worker3

- name: Destroy storage pools
  command: virsh pool-destroy {{ item }}
  ignore_errors: yes
  loop:
    - bootstrap
    - control1
    - control2
    - control3
    - worker1
    - worker2
    - worker3
    - worker1-ocs
    - worker2-ocs
    - worker3-ocs

- name: Remove storage directories
  shell: |
    rm -rf {{ cluster_vms_storage_base_dir }} &> /dev/null