---
apiVersion: v1
kind: Secret
metadata:
  name: {{ cert_manager_cloudflare_token_secret_name }}
  namespace: {{ cloudflare_api_token_namespace }}
type: Opaque
stringData:
  {{ cert_manager_cloudflare_token_secret_key }}: "{{ cloudflare_api_token }}"
