apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: {{ inventory_hostname }}-br
spec:
  nodeSelector: 
    kubernetes.io/hostname: {{ inventory_hostname }}
  desiredState:
    interfaces:
      - name: {{ bridge_interface_name }}
        description: Linux bridge using {{ secondary_nic }} device
        type: linux-bridge
        state: up
        ipv4:
          dhcp: true
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: {{ secondary_nic }}