
- name: check ssh to remote hosts works
  shell: "ssh -oStrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/.ssh/id_rsa core@{{ inventory_hostname }} hostname"
  register: ssh_connection_test
  ignore_errors: yes

- debug:
    msg: 
      - "{{ ssh_connection_test.stdout }}"
      - "Exit code was {{ ssh_connection_test.rc }}"