
- name: General vars for VMs
  set_fact:
    vm_name: "{{ node.custom_vm_name }}-{{ ocp_cluster_name }}"

- name: Destroy storage pools
  command: virsh pool-destroy {{ vm_name }}-data
  ignore_errors: yes
  become: True

- name: Check to see if disk path is valid
  ansible.builtin.stat:
    path: "{{ node.data_disk_path }}"
  register: p
  become: True
  when: node.data_disk_path is defined

- name: Remove data storage directories
  shell: |
    rm -rf {{ node.data_disk_path }}/* &> /dev/null
  when: 
    - node.data_disk_path is defined
    - p.stat.isdir is defined and p.stat.isdir
  become: True

- name: Zap raw disks for cluster storage
  shell: |
    sgdisk --zap-all --clear {{ node.fast_data_disk_path_on_host }}
    wipefs -a {{ node.fast_data_disk_path_on_host }}
    kpartx -f -v {{ node.fast_data_disk_path_on_host }}
  become: True
  when: 
    - node.fast_data_disk_path_on_host is defined