---
- name: General vars for VMs
  set_fact:
    vm_name: "{{ custom_vm_name }}-{{ ocp_cluster_name }}"

- name: Destroy storage pools
  command: virsh pool-destroy {{ vm_name }}-data
  ignore_errors: yes

- name: Check to see if disk path is valid
  ansible.builtin.stat:
    path: "{{ data_disk_path }}"
  register: p

- name: Remove data storage directories
  shell: |
    rm -rf {{ data_disk_path }}/* &> /dev/null
  when: p.stat.isdir is defined and p.stat.isdir

- name: Zap raw disks for cluster storage
  shell: |
    sgdisk --zap-all --clear {{ fast_data_disk_path_on_host }}
    wipefs -a {{ fast_data_disk_path_on_host }}