apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage
  namespace: local-storage
spec:
  channel: "4.7"
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace