---
- name: Eject Virtual CD block
  block:
    - name: Create Session for eject virtual cd drive
      dellemc.openmanage.idrac_session:
        hostname: "{{ lookup('community.general.dig', 'idrac-' ~ inventory_hostname) }}"
        username: "{{ idrac_admin_user }}"
        password: "{{ idrac_admin_password }}"
        validate_certs: False
        state: present
      register: eject_login_info
      ignore_errors: True

    - name: Eject Virtual CD Drive
      dellemc.openmanage.idrac_virtual_media:
        idrac_ip: "{{ lookup('community.general.dig', 'idrac-' ~ inventory_hostname) }}"
        idrac_user: "{{ idrac_admin_user }}"
        idrac_password: "{{ idrac_admin_password }}"
        validate_certs: False
        force: True
        virtual_media:
          - insert: false
      ignore_errors: True

  always:
    - name: Delete Session
      dellemc.openmanage.idrac_session:
        hostname: "{{ lookup('community.general.dig', 'idrac-' ~ inventory_hostname) }}"
        x_auth_token: "{{ eject_login_info.x_auth_token }}"
        session_id: "{{ eject_login_info.session_data.Id }}"
        validate_certs: False
        state: absent
      when: eject_login_info.x_auth_token is defined
      ignore_errors: True
