- include_role:
    name: hashicorp-vault-get-token
  run_once: true

- include_role:
    name: hashicorp-vault-read-secret
  vars: 
    secret_path: "{{ cluster_common_vault_secret_path }}"
  run_once: true

- set_fact:
    rhcos_ssh_pub_key: "{{ vault_payload[rhcos_ssh_pub_key_vault_key] }}"
    additional_trust_bundle: "{{ vault_payload[additional_trust_bundle_vault_key] }}"
    pull_secret: '{{ vault_payload[pull_secret_vault_key] | b64decode | string }}'
  run_once: true
