---
- include_vars:
    file: "{{ config }}"
  run_once: true

- include_vars:
    file: "{{ item }}"
  loop: "{{ configs }}"
  run_once: true

- include_tasks: infra-config-load.yaml
  when: cluster_role == "infra"

- include_tasks: tenant-config-load.yaml
  when: cluster_role == "tenant"

