- name: Get infra host cluster storageclass names
  k8s_info:
    api_version: v1
    kind: ConfigMap
    name: cluster-metadata
    namespace: cluster-metadata
    kubeconfig: "{{ infra_cluster_kubeconfig }}"
  register: cluster_metadata
  until: cluster_metadata.resources is defined
  retries: 5
  delay: 20

- debug:
    var: cluster_metadata
    
- set_fact:
    infra_cluster_storage_class_name: "{{ cluster_metadata.resources[0].data['standard-sc'] }}"
    infra_cluster_fast_storage_class_name: "{{ cluster_metadata.resources[0].data['fast-sc'] }}"