---
- name: Set ignition file
  set_fact:
    ignition_file: "{{ ocp_install_dir }}/{% if custom_vm_type == 'master' %}master.ign{% elif custom_vm_type == 'worker' %}worker.ign{% else %}bootstrap-pointer.ign{% endif %}"

- debug:
    msg:
      - "ignition_file: {{ ignition_file }}"

- name: Set ignition content
  set_fact:
    ignition_content: "{{ lookup('file', ignition_file) }}"

- debug:
    var: ignition_content

- name: Get RHCOS image for current version of OCP
  shell: openshift-install coreos print-stream-json | jq .architectures.x86_64.images.kubevirt
  shell:
    cmd: "{{ staging_dir }}/openshift-install coreos print-stream-json"
  register: os_stream_json

- name: Set Core OS image for current OCP release
  set_fact:
    coreos_image_url: '{{ os_stream_json.stdout | from_json | json_query(coreos_version_json_query) }}'
    coreos_version: '{{ os_stream_json.stdout | from_json | json_query("architectures.x86_64.images.kubevirt.release") }}'
  vars:
    coreos_version_json_query: 'architectures.x86_64.images.kubevirt.["digest-ref"][0]'
    
- debug:
    msg:
      -  'Core OS Version: {{ coreos_version }}'
      -  'Core OS image URL: {{ coreos_image_url }}'

- name: Apply vm yaml
  k8s:
    state: present
    definition: "{{ lookup('template', 'rhcos-vm.yaml') }}"
