apiVersion: v1
baseDomain: {{ base_domain }}
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities: 
    - CSISnapshot
    - Console
    - Storage
    - marketplace
    - OperatorLifecycleManager
    - OperatorLifecycleManagerV1
    - openshift-samples
    - NodeTuning
    - Ingress
compute:
- name: worker
  replicas: {{ groups['worker'] | length }}
  hyperthreading: Enabled
  architecture: amd64
controlPlane:
  name: master 
  replicas: {{ groups['control'] | length }}
  hyperthreading: Enabled   
  architecture: amd64
metadata:
  name: {{ ocp_cluster_name }}
networking:
  machineNetwork:
  - cidr: 192.0.0.0/8
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: {{ ocp_network_type}}
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
additionalTrustBundle: |
{{ additional_trust_bundle | indent(width=2, first=true) }}
pullSecret: '{{ pull_secret | trim  }}'
sshKey: '{{ rhcos_ssh_pub_key }}'