--- 
- name: Destroy storage pools
  shell: |
    virsh pool-destroy {{ ocp_cluster_fqdn }}
    virsh pool-undefine {{ ocp_cluster_fqdn }}
  ignore_errors: True
  become: True

- name: Remove storage directories
  shell: |
    rm -rf {{ cluster_vms_storage_base_dir }} &> /dev/null
  become: True

