---
- name: Create Nmstate namespace
  k8s:
    state: present
    definition: "{{ lookup('template', item ) }}"
  with_items:
    - 01-nmstate-ns.yaml
    - 02-operator-group.yaml
    - 03-nmstate-sub.yaml

- name: sleep for 5 seconds
  wait_for:
    timeout: 10

- name: Wait until nmstate Operator installation has succeeded
  shell:
    cmd: oc get csv $(oc get subscriptions.operators.coreos.com kubernetes-nmstate-operator -n openshift-nmstate -o=jsonpath='{.status.currentCSV}') -n openshift-nmstate -o=jsonpath='{.status.phase}'
  register: result
  until: result.stdout == "Succeeded"
  retries: 100
  delay: 5

- name: Create Nmstate instance
  k8s:
    state: present
    definition: "{{ lookup('template', '04-nmstate-instance.yaml') }}"
