---

- name: Create Nmstate namespace
  k8s:
    state: present
    definition: "{{ lookup('template', '01-nmstate-ns.yaml') }}"

- name: sleep for 5 seconds
  wait_for:
    timeout: 5

  
- name: Create Nmstate Subscription
  k8s:
    state: present
    definition: "{{ lookup('template', '02-nmstate-sub.yaml') }}"

- name: sleep for 20 seconds
  wait_for:
    timeout: 20

- name: Wait until nmstate Operator installation has succeeded
  shell:
    cmd: oc get csv $(oc get subscriptions.operators.coreos.com kubernetes-nmstate-operator -n openshift-nmstate -o=jsonpath='{.status.currentCSV}') -n openshift-nmstate -o=jsonpath='{.status.phase}'
  register: result
  until: result.stdout == "Succeeded"
  retries: 100
  delay: 5

- name: Create Nmstate instance
  k8s:
    state: present
    definition: "{{ lookup('template', '03-nmstate-instance.yaml') }}"