
- name: Get nodeport of the ingress service
  vars:
    jsonpath: '{.spec.ports[?(@.port==443)].nodePort}'
  shell:
    cmd: "{{ oc_bin }} --kubeconfig {{ cluster_kubeconfig }} get services -n openshift-ingress router-nodeport-default -o=jsonpath='{{ jsonpath }}'"
  register: ingress_nodeport_cmd
  until: ingress_nodeport_cmd.rc == 0
  retries: 120
  delay: 5

- name: Get IP of cluster ingress from DNS
  shell:
    cmd: host {{ hypershift_ingress_domain }} | awk '{print $4}'
  register: hostip_cmd

- set_fact:
    ingress_nodeport: "{{ ingress_nodeport_cmd.stdout }}"
    load_balancer_ip: "{{ hostip_cmd.stdout }}"


- name: Create ingress service
  k8s:
    state: present
    definition: "{{ lookup('template', 'cluster-ingress-service.yaml') }}"


- name: Create ingress route
  k8s:
    state: present
    definition: "{{ lookup('template', 'cluster-ingress-route.yaml') }}"