apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    ozone.io/coreos-version: {{ coreos_version }}
  name: {{ custom_vm_name }}
  namespace: {{ ocp_cluster_name }}
  labels:
    app: {{ custom_vm_name }}
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhcos-{{ custom_vm_name }}-disk-0
      spec:
        source:
          registry:
            pullMethod: node
            url: 'docker://{{ coreos_image_url }}'
        storage:
          accessModes:
            - {{ infra_cluster_storage_access_mode }}
          resources:
            requests:
              storage: 30Gi
          storageClassName: {{ infra_cluster_storage_class_name }}
          volumeMode: {{ infra_cluster_storage_volume_mode }}
{% if custom_vm_type == 'master' %}    
    - metadata:
        name: rhcos-{{ custom_vm_name }}-disk-1
      spec:
        pvc:
          accessModes:
            - {{ infra_cluster_storage_access_mode }}
          resources:
            requests:
              storage: 5Gi
          storageClassName: {{ infra_cluster_storage_class_name }}
          volumeMode: {{ infra_cluster_storage_volume_mode }}
        source:
          blank: {}  
{% endif %}          
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rhcos
            - disk:
                bus: virtio
              name: cloudinitvolume
{% if custom_vm_type == 'master' %}    
            - disk:
                bus: virtio
              name: disk-1
{% endif %}                    
          interfaces:
            - bridge: {}
              macAddress: '{{ custom_mac }}'
              model: virtio
              name: nic-0
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 16Gi
            cpu: "4"
      hostname: {{ custom_vm_name }}
      networks:
        - multus:
            networkName: {{ infra_cluster_bridge_name }}
          name: nic-0
      terminationGracePeriodSeconds: 90
      volumes:
        - dataVolume:
            name: rhcos-{{ custom_vm_name }}-disk-0
          name: rhcos
        - cloudInitConfigDrive:
            secretRef:
              name: {{ custom_vm_type }}-ign
          name: cloudinitvolume
{% if custom_vm_type == 'master' %}
        - dataVolume:
            name: rhcos-{{ custom_vm_name }}-disk-1
          name: disk-1
{% endif %}          
