---
- name: Get cluster kubeconfig
  include_role:
    name: common/bitwarden-read-secret
  vars: 
    project_name: "{{ bitwarden_k8s_clusters_project_name }}"

- name: Copy kubeconfig to staging dir
  copy:
    content: "{{ (bitwarden_payload | selectattr('key', 'equalto', cluster + '-kubeconfig') | first).value | b64decode }}"
    dest: "{{ staging_dir }}/{{ cluster }}-kubeconfig"
    mode: "0660"
...