---
- name: Get cluster secrets from Bitwarden
  include_role:
    name: common/bitwarden-read-secret
  vars: 
    project_name: "{{ bitwarden_homelab_project_name }}"

- name: Set cluster secret vars
  set_fact:
    idrac_admin_user: "{{ (bitwarden_payload | selectattr('key', 'equalto', idrac_admin_user_vault_key) | first).value }}"
    idrac_admin_password: "{{ (bitwarden_payload | selectattr('key', 'equalto', idrac_admin_password_vault_key) | first).value }}"
    rhcos_ssh_private_key: "{{ (bitwarden_payload | selectattr('key', 'equalto', rhcos_ssh_private_key_vault_key) | first).value }}"
    rhcos_ssh_pub_key: "{{ (bitwarden_payload | selectattr('key', 'equalto', rhcos_ssh_pub_key_vault_key) | first).value }}"
    additional_trust_bundle: "{{ (bitwarden_payload | selectattr('key', 'equalto', additional_trust_bundle_vault_key) | first).value }}"
    pull_secret: "{{ (bitwarden_payload | selectattr('key', 'equalto', pull_secret_vault_key) | first).value | b64decode | string }}"
...