---
- set_fact:
    config_dir: "{{ role_path }}/../../../../../ocp-cluster-vars/vars/{{ cluster_name }}"

- include_vars:
    file: "{{ config_dir }}/main.yaml"
  run_once: true
  when: action == "base"

- include_vars:
    file: "{{ item }}"
  loop: "{{ configs }}"
  run_once: true
  when: action == "base"

- include_tasks: common-config-load.yaml

- include_tasks: infra-config-load.yaml
  when: 
    - cluster_role == "infra"
    - action == "cluster-config"

- include_tasks: tenant-config-load.yaml
  when:
    - cluster_role == "tenant"
    - action == "cluster-config"
