---

- name: Run OCP Ignition Configs
  shell:
    chdir: "{{ staging_dir }}"
    cmd: "{{ staging_dir }}/openshift-install create ignition-configs --dir {{ ocp_install_dir }}"

- include_role:
    name: hashicorp-vault-get-token

- include_role:
    name: openshift-credentials-store
  vars: 
    path: "{{ ocp_cluster_name }}"
    data: 
      kubeconfig: "{{ lookup('file', kubeconfig_src_path) | b64encode }}"
      kubeadmin-password: "{{ lookup('file', kubeadmin_password_src_path) | b64encode }}"

- name: Copy kubeconfig to staging dir
  copy:
    src: "{{ kubeconfig_src_path }}"
    dest: "{{ cluster_kubeconfig }}"
    mode: "0660"
