
# Create base directory for cluster vm pools
- name: Create Pool directory
  delegate_to: "{{ groups.hypervisor[0] }}"
  file:
    state: directory
    path: "{{ cluster_vms_storage_base_dir }}"
    group: "qemu"
    owner: "qemu"
    mode: "0770"
  become: True

- name: Create Storage Pool for Cluster
  delegate_to: "{{ groups.hypervisor[0] }}"
  shell: |
    virsh pool-define-as --name {{ ocp_cluster_fqdn }} --type dir --target {{ cluster_vms_storage_base_dir }}
    virsh pool-autostart {{ ocp_cluster_fqdn }}
    virsh pool-start {{ ocp_cluster_fqdn }}
  become: True
  run_once: True

- name: Create qcow image for host os drive
  delegate_to: "{{ groups.hypervisor[0] }}"
  shell: | 
    qemu-img create -f qcow2 {{ cluster_vms_storage_base_dir }}/{{ inventory_hostname }}.qcow2 {{ rhcos_os_disk_size }}
  become: True

# ## Create a second storage pool if vm is worker
- name: Create additional storage on HV host
  include_tasks: create-storage-on-hv-host.yaml
  vars:
    disk: "{{ item }}"
  loop: "{{ disks | list }}"
  when: disks is defined

- name: "Process KVM VM XML spec for {{ inventory_hostname }} "
  delegate_to: "{{ groups.hypervisor[0] }}"
  template: 
    src: vm_spec.j2
    dest: "{{ staging_dir }}/{{ inventory_hostname }}.xml"

- name: "Create vm for host {{ inventory_hostname }}"
  delegate_to: "{{ groups.hypervisor[0] }}"
  shell: |
    virsh define --file {{ staging_dir }}/{{ inventory_hostname }}.xml
    virsh autostart {{ inventory_hostname }}
    virsh start {{ inventory_hostname }}
  become: True
