---
- name: Create OCP manifests
  environment:
    PATH: "{{ staging_dir }}:{{ lookup('env', 'PATH') }}"
  shell: |
    {{ openshift_install_bin }} agent create image --dir {{ ocp_install_dir }}

- include_role:
    name: deploy/openshift-credentials-store
  vars: 
    path: "{{ ocp_cluster_fqdn }}"
    data: 
      kubeconfig: "{{ lookup('file', kubeconfig_src_path) | b64encode }}"
      kubeadmin-password: "{{ lookup('file', kubeadmin_password_src_path) | b64encode }}"

- name: Copy kubeconfig to staging dir
  copy:
    src: "{{ kubeconfig_src_path }}"
    dest: "{{ cluster_kubeconfig }}"
    mode: "0660"

- name: Copy agent ISO to hypervisor host
  delegate_to: "{{ groups.hypervisor[0] }}"
  copy:
    src: "{{ ocp_install_dir }}/agent.x86_64.iso"
    dest: "{{ staging_dir }}/agent.x86_64.iso"
    mode: "0660"
  when: platform == "kvm" or  
        platform == "kvm_bm"

- name: Copy agent ISO to hypervisor host
  delegate_to: "{{ groups.hypervisor[0] }}"
  copy:
    src: "{{ ocp_install_dir }}/agent.x86_64.iso"
    dest: "{{ staging_dir }}/agent.x86_64.iso"
    mode: "0660"
  when: platform == "kvm" or  
        platform == "kvm_bm"

- name: Copy agent ISO to Webserver host
  delegate_to: "{{ groups.webserver[0] }}"
  become: True
  copy:
    src: "{{ ocp_install_dir }}/agent.x86_64.iso"
    dest: "{{ web_server.files_root_path }}/agent.x86_64.iso"
    mode: "0666"
  when: platform == "kvm_bm" or
        platform == "O^3"
    