---
- name: Create OCP manifests
  environment:
    PATH: "{{ staging_dir }}:{{ lookup('env', 'PATH') }}"
  shell: |
    {{ openshift_install_bin }} agent create image --dir {{ ocp_install_dir }}

- name: Copy kubeconfig to staging dir
  copy:
    src: "{{ kubeconfig_src_path }}"
    dest: "{{ cluster_kubeconfig }}"
    mode: "0660"

- name: Store cluster kubeconfig
  include_role:
    name: deploy/openshift-credentials-store
  vars: 
    secret_key: "{{ ocp_cluster_fqdn }}-kubeconfig"
    secret_data: "{{ lookup('file', cluster_kubeconfig) | b64encode }}"

- name: Store cluster admin password
  include_role:
    name: deploy/openshift-credentials-store
  vars: 
    secret_key: "{{ ocp_cluster_fqdn }}-kubeadmin-password"
    secret_data: "{{ lookup('file', kubeadmin_password_src_path) | b64encode }}"

- name: Copy agent ISO to hypervisor host
  delegate_to: "{{ groups.get('hypervisor', ['localhost']) | first }}"
  copy:
    src: "{{ ocp_install_dir }}/agent.x86_64.iso"
    dest: "{{ staging_dir }}/agent.x86_64.iso"
    mode: "0660"
  when:
    - "'hypervisor' in groups"
    - "groups['hypervisor'] | length > 0"
    - platform == "kvm" or platform == "kvm_bm"

- name: Copy agent ISO to Webserver host
  delegate_to: "{{ groups.get('webserver', ['localhost']) | first }}"
  become: True
  copy:
    src: "{{ ocp_install_dir }}/agent.x86_64.iso"
    dest: "{{ web_server.files_root_path }}/agent.x86_64.iso"
    mode: "0666"
  when:
    - "'webserver' in groups"
    - "groups['webserver'] | length > 0"
    - platform == "kvm_bm" or platform == "O^3"
    