---
- name: Create OCP manifests
  environment:
    PATH: "{{ staging_dir }}:{{ lookup('env', 'PATH') }}"
  shell: |
    {{ staging_dir }}/openshift-install agent create image --dir {{ ocp_install_dir }}

- include_role:
    name: deploy/openshift-credentials-store
  vars: 
    path: "{{ ocp_cluster_name }}"
    data: 
      kubeconfig: "{{ lookup('file', kubeconfig_src_path) | b64encode }}"
      kubeadmin-password: "{{ lookup('file', kubeadmin_password_src_path) | b64encode }}"

- name: Copy kubeconfig to staging dir
  copy:
    src: "{{ kubeconfig_src_path }}"
    dest: "{{ cluster_kubeconfig }}"
    mode: "0660"

- name: Copy agent ISO to hypervisor host
  delegate_to: "{{ groups.hypervisor[0] }}"
  copy:
    src: "{{ ocp_install_dir }}/agent.x86_64.iso"
    dest: "{{ staging_dir }}/agent.x86_64.iso"
    mode: "0660"



# - name: Create remote directory for cluster ignition files
#   file:
#     path: "{{ web_server_files_cluster_path }}"
#     state: directory
#     mode: '0655'
#   delegate_to: "{{ web_server.name }}"
#   become: true

# - name: Copy ignition files to webserver
#   copy:
#     src: "{{ ocp_install_dir }}/{{ item }}"
#     dest: "{{ web_server_files_cluster_path }}"
#     mode: '0644'
#   loop:
#     - "master.ign"
#     - "worker.ign"
#     - "bootstrap.ign"
#   delegate_to: "{{ web_server.name }}"
#   become: true