---

- name: remove OCP install folder
  file:
    state: absent
    path: "{{ ocp_install_dir }}"


- name: Create OCP install folder and backup
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ ocp_install_dir }}"
    - "{{ staging_backup_dir }}"
    - "{{ staging_dir }}/calico"


- name: Process OCP install config template
  template: 
    src: install-config.yaml
    dest: "{{ item }}"
  with_items:
    - "{{ ocp_install_dir }}"
    - "{{ staging_backup_dir }}"


- name: Create OCP manifests
  shell:
    chdir: "{{ staging_dir }}"
    cmd: "{{ staging_dir }}/openshift-install create manifests --dir {{ ocp_install_dir }}"

# Separate partition for ETCD for better performance
- name: Process machine config for disk partitioning
  template: 
    src: 98-etcd-partition.yaml
    dest: "{{ ocp_install_dir }}/manifests"
  when: platform == "O^3"


# - name: Get calico manifests
#   shell:
#     chdir: "{{ staging_dir }}/calico"
#     cmd:  |
#       "wget {{ calico_archive_uri }}"
#       "tar xvf ocp.tgz"
#       "cp ./ocp/* {{ ocp_install_dir }}/manifests/"
#   when: ocp_network_type == "Calico"


- name: Download Calico archive
  get_url:
    url: "{{ calico_archive_uri }}"
    dest: "{{ staging_dir }}/calico"
  when: ocp_network_type == "Calico"

- name: Extract Calico archive to manifests directory
  unarchive:
    src: "{{ staging_dir }}/calico/ocp.tgz"
    dest: "{{ staging_dir }}/calico"
  when: ocp_network_type == "Calico"

- name: Copy Calico manifests to OCP manifests folder
  copy:
    src: "{{ staging_dir }}/calico/ocp/"
    dest: "{{ ocp_install_dir }}/manifests/"
    mode: '0666'
  become: true
  when: ocp_network_type == "Calico"

