---
- name: Delete ingress service
  k8s:
    state: absent
    definition: "{{ lookup('template', 'cluster-ingress-service.yaml') }}"

- name: Delete ingress route
  k8s:
    state: absent
    definition: "{{ lookup('template', 'cluster-ingress-route.yaml') }}"

- name: Destroy Hypershift Cluster
  shell:
    cmd: "{{ hypershift_cli_path }} destroy cluster kubevirt --name {{ ocp_cluster_name }}"
  ignore_errors: true

