---
- name: "Zap, wipe and update partion table for {{ inventory_hostname }} -> {{ disk }}"
  vars:
    ansible_ssh_private_key_file: "{{ rhcos_ssh_private_key_file }}"
    ansible_python_interpreter: /usr/libexec/platform-python
  remote_user: core
  become: True
  shell: |
    sgdisk --zap-all --clear {{ disk }};
    wipefs -a {{ disk }};
    kpartx -f -v {{ disk }};
    rm -rf /mnt/local-storage/*;
  register: clean_result
  until: clean_result.rc == 0
  retries: 10
  delay: 20


- name: Drive clean Result 
  debug:
    msg: 
      - "stdout: {{ clean_result.stdout }}"
      - "stdout: {{ clean_result.stderr }}"
