---

- name: Create remote directory for cluster ignition files
  delegate_to: "{{ groups['webserver'][0] }}"
  become: yes
  file:
    path: "{{ web_server_files_cluster_path }}"
    state: directory
    mode: '0655'

- name: Copy ignition files to webserver
  delegate_to: "{{ groups['webserver'][0] }}"
  become: yes
  copy:
    src: "{{ ocp_install_dir }}/{{ item }}"
    dest: "{{ web_server_files_cluster_path }}"
    mode: '0644'
  loop:
    - "master.ign"
    - "worker.ign"
    - "bootstrap.ign"
  