---
- name: Copy ignition files to webserver
  copy:
    src: "{{ ocp_install_dir }}/{{ item }}"
    dest: "{{ web_server_files_cluster_path }}"
    mode: '0644'
  loop:
    - "master.ign"
    - "worker.ign"
    - "bootstrap.ign"
  delegate_to: "{{ web_server.name }}"
  