---

- name: Create http folder for cluster
  file:
    state: directory
    path: "{{ http_file_server_path }}"

- name: Copy ignition files to webserver
  copy:
    src: "{{ ocp_install_dir }}/{{ item }}"
    dest: "{{ http_file_server_path }}"
    mode: '0644'
  loop:
    - "master.ign"
    - "worker.ign"
    - "bootstrap.ign"