apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: standard
        default: true
        thinPoolConfig:
          name: {{ lvms.fast.name }}-thin-pool
          overprovisionRatio: 20
          sizePercent: 90
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - values:
                {% for node in groups['worker'] %} 
                  {% for disk in hostvars[node].disks %} 
                    {% if disk.speed == 'standard' %} 
                    - "{{ node }}" 
                    {% endif %} 
                  {% endfor %} 
                {% endfor %} 
                  key: kubernetes.io/hostname
                  operator: In        
        deviceSelector:
          forceWipeDevicesAndDestroyAllData: True
          optionalPaths :
          {% for disk in standard_disks %}
            - "{{ disk }}"
          {% endfor %}          
      - name: fast
        thinPoolConfig:
          name: {{ lvms.fast.name }}-thin-pool
          overprovisionRatio: 20
          sizePercent: 90
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - values:
                {% for node in groups['worker'] %} 
                  {% for disk in  hostvars[node].disks %} 
                    {% if disk.speed == 'fast' %} 
                    - "{{ node }}" 
                    {% endif %} 
                  {% endfor %} 
                {% endfor %} 
                  key: kubernetes.io/hostname
                  operator: In
        deviceSelector:
          forceWipeDevicesAndDestroyAllData: True
          optionalPaths :
          {% for disk in fast_disks %}
            - "{{ disk }}"
          {% endfor %}   