apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: "{{ lvms.standard.name }}"
        default: true
        thinPoolConfig:
          name: {{ lvms.fast.name }}-thin-pool
          overprovisionRatio: 20
          sizePercent: 90
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - values:
                {% for node in groups['worker'] %}
                  {% for disk in node.disks %}
                    {% if disk.speed == 'standard' %}
                    - "{{ inventory_hostname }}"
                    {% endif %}
                  {% endfor %}          
                {% endfor %}   
                  key: kubernetes.io/hostname
                  operator: In        
        deviceSelector:
          forceWipeDevicesAndDestroyAllData: True
          optionalPaths :
          {% for node in groups['worker'] %}
            {% for disk in node.disks %}
              {% if disk.speed == 'standard' %}
            - "{{ disk.path }}"
              {% endif %}
            {% endfor %}          
          {% endfor %}          
      - name: "{{ lvms.fast.name }}"
        thinPoolConfig:
          name: {{ lvms.fast.name }}-thin-pool
          overprovisionRatio: 20
          sizePercent: 90
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                - values:
                {% for node in groups['worker'] %}
                  {% for disk in node.disks %}
                    {% if disk.speed == 'fast' %}
                    - "{{ inventory_hostname }}"
                    {% endif %}
                  {% endfor %}          
                {% endfor %}   
                  key: kubernetes.io/hostname
                  operator: In  
        deviceSelector:
          forceWipeDevicesAndDestroyAllData: True
          optionalPaths :
          {% for node in groups['worker'] %}
            {% for disk in node.disks %}
              {% if disk.speed == 'fast' %}
            - "{{ disk.path }}"
              {% endif %}
            {% endfor %}          
          {% endfor %} 