---

- name: Delete hyperconverged cluster yaml
  community.kubernetes.k8s:
    state: absent
    definition: "{{ lookup('template', '03-cnv-hc.yaml') }}"

- name: sleep for 30 seconds
  wait_for:
    timeout: 20


- name: Delete OpenShift Virtualization Subscription yaml
  community.kubernetes.k8s:
    state: absent
    definition: "{{ lookup('template', '02-cnv-sub.yaml') }}"

- name: sleep for 20 seconds
  wait_for:
    timeout: 20


- name: Delete OpenShift Virtualization NS and OG yaml
  community.kubernetes.k8s:
    state: absent
    definition: "{{ lookup('template', '01-cnv-ns-og.yaml') }}"

- name: sleep for 5 seconds
  wait_for:
    timeout: 5






