---
- name: General vars for VMs
  set_fact:
    vm_name: "{{ custom_vm_name }}-{{ ocp_cluster_name }}"


- name: Destroy storage pools
  command: virsh pool-destroy {{ vm_name }}-ocs
  ignore_errors: yes


- name: Check to see if OCS path is valid
  ansible.builtin.stat:
    path: "{{ ocs_disk_path }}"
  register: p

- name: Remove OCS storage directories
  shell: |
    rm -rf {{ ocs_disk_path }}/* &> /dev/null
  when: p.stat.isdir is defined and p.stat.isdir