apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: {{ ocp_cluster_name }}
  namespace: clusters
spec:
  configuration:
    oauth:
      identityProviders:
        - name: my_htpasswd_provider 
          mappingMethod: claim 
          type: HTPasswd
          htpasswd:
            fileData:
              name: htpass-secret-{{ ocp_cluster_name }}
  autoscaling: {}
  controllerAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: {{ base_domain }}
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 8Gi
          storageClassName: {{ infra_cluster_fast_storage_class_name }}
        restoreSnapshotURL: null
        type: PersistentVolume
    managementType: Managed
  fips: false
  infraID: {{ infra_cluster_name }}
  networking:
    clusterNetwork:
    - cidr: 10.132.0.0/14
    networkType: OVNKubernetes
    serviceNetwork:
    - cidr: 172.31.0.0/16
  platform:
    kubevirt: {}
    type: KubeVirt
  pullSecret:
    name: "{{ ocp_cluster_name }}-pull-secret"
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.13.3-x86_64
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
  - service: OVNSbDb
    servicePublishingStrategy:
      type: Route
  sshKey:
    name: "{{ ocp_cluster_name }}-ssh-key"
