---

- set_fact:
    tenant_cluster_kubeconfig: "{{ staging_dir }}/configs/{{ ocp_cluster_name }}"
    kubevirt_csi_repo: "{{ staging_dir }}/kubevirt-csi-driver"
    kubevirt_csi_service_kubeconfig_path: "{{ staging_dir }}/{{ kubevirt_csi_service_kubeconfig }}"


- name: Clone kubevirt csi repo
  git:
    repo: https://github.com/arvin-a/csi-driver.git
    dest: "{{ kubevirt_csi_repo }}"
    version: kustomize-installer

- debug:
    msg: 
      - "TENANT_CLUSTER_NAME: {{ ocp_cluster_name }}"
      - "TENANT_CLUSTER_KUBEECONFIG: {{ tenant_cluster_kubeconfig }}"
      - "INFRA_CLUSTER_KUBECONFIG: {{ infra_cluster_kubeconfig }}"
      - "INFRA_CLUSTER_TENANT_NAMESPACE: {{ infra_cluster_tenant_namespace }}"
      - "INFRA_STORAGE_CLASS_NAME: {{ kubevirt_csi_infra_cluster_sc }}"

- name: Run kubevirt csi installer
  environment:
    TENANT_CLUSTER_NAME: "{{ ocp_cluster_name }}"
    TENANT_CLUSTER_KUBEECONFIG: "{{ tenant_cluster_kubeconfig }}"
    INFRA_CLUSTER_KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
    INFRA_CLUSTER_TENANT_NAMESPACE: "{{ infra_cluster_tenant_namespace }}"
    INFRA_STORAGE_CLASS_NAME: "{{ kubevirt_csi_infra_cluster_sc }}"
  shell:
    chdir: "{{ kubevirt_csi_repo }}/deploy"
    cmd: "./install-kubevirt-csi.sh"
