---
- set_fact:
    tenant_cluster_kubeconfig: "{{ staging_dir }}/configs/{{ ocp_cluster_name }}"
    kubevirt_csi_repo: "{{ staging_dir }}/kubevirt-csi-driver"
    kubevirt_csi_service_kubeconfig_path: "{{ staging_dir }}/{{ kubevirt_csi_service_kubeconfig }}"

- debug:
    msg: 
      - "TENANT_CLUSTER_NAME: {{ ocp_cluster_name }}"
      - "TENANT_CLUSTER_KUBEECONFIG: {{ tenant_cluster_kubeconfig }}"
      - "INFRA_CLUSTER_KUBECONFIG: {{ infra_cluster_kubeconfig }}"
      - "INFRA_CLUSTER_TENANT_NAMESPACE: {{ infra_cluster_tenant_namespace }}"
      - "INFRA_STORAGE_CLASS_NAME: {{ kubevirt_csi_infra_cluster_sc }}"

- name: Clone kubevirt csi repo
  git:
    repo: https://github.com/arvin-a/csi-driver.git
    dest: "{{ kubevirt_csi_repo }}"
    version: main

- name: Deploy infra service account
  shell:
    chdir: "{{ kubevirt_csi_repo }}/deploy"
    cmd: "oc -n {{ infra_cluster_tenant_namespace }} apply -f ./infra-cluster-service-account.yaml"

- name: Deploy the tenant resources not including the controller
  shell:
    chdir: "{{ kubevirt_csi_repo }}/deploy"
    cmd: "oc apply --kubeconfig {{ tenant_cluster_kubeconfig }} --kustomize ./tenant/overlay"

- name: Deploy the tenant resources not including the controller
  shell:
    chdir: "{{ kubevirt_csi_repo }}/deploy"
    cmd: "oc apply --kustomize ./controller-infra/overlay"

