apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: "{{ data_disks.standard.name }}"
        default: true
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
        deviceSelector:
          paths:
          - "{{ data_disks.standard.disk_path }}"
      - name: "{{ data_disks.fast.name }}"
        thinPoolConfig:
          name: thin-pool-2
          overprovisionRatio: 10
          sizePercent: 90
        deviceSelector:
          paths:
          - "{{ data_disks.fast.disk_path }}"