apiVersion: v1
baseDomain: {{ base_domain }}
capabilities:
  # baselineCapabilitySet: None
  # additionalEnabledCapabilities: 
  # - MachineAPI
  # - marketplace
  # - OperatorLifecycleManager
  # - openshift-samples
  # - Console
  # - Storage
  # - CSISnapshot
  # - NodeTuning
  # - Build
  # - DeploymentConfig
  # - Ingress
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3
metadata:
  name: {{ ocp_cluster_name }}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: {{ ocp_network_type}}
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
additionalTrustBundle: |
{{ additional_trust_bundle | indent(width=2, first=true) }}
pullSecret: '{{ pull_secret | trim  }}'
sshKey: '{{ rhcos_ssh_pub_key }}'