apiVersion: v1
baseDomain: {{ base_domain }}
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: {{ worker_count }}
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3
metadata:
  name: {{ ocp_cluster_name }}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
additionalTrustBundle: |
{{ additional_trust_bundle | indent(width=2, indentfirst=true) }}
pullSecret: '{{ pull_secret }}'
sshKey: '{{ rhcos_ssh_pub_key }}'