platform: "libvirt"
ocp_cluster_name: "ocp-infra1"
cluster_kubeconfig: "{{ kubeconfig_dir }}/{{ ocp_cluster_name }}"
staging_dir: "{{ staging_base_dir }}/{{ ocp_cluster_name }}"
ocp_install_dir: "{{ staging_dir }}/ocp-install"


# OCP Vars
ocp_bin_version: "4.7"
ocp_bin_channel: "fast"
rhcos_bin_qcow_url: "{{ rhcos_bin_release_url }}/{{ libvirt_rhcos_bin_archive_name }}"
rhcos_bin_archive_name: "{{ libvirt_rhcos_bin_archive_name }}"
rhcos_bin_file_name: "{{ libvirt_rhcos_bin_file_name }}"

# Libvirt vars
cluster_vms_storage_base_dir: "/storage/p4600-1/kvm/{{ ocp_cluster_name }}"
base_qcow: "{{ staging_dir }}/{{ rhcos_bin_file_name }}"

resized_base_qcow_disk_size: "100G"
resized_base_qcow: "{{ staging_dir }}/resized_{{ rhcos_bin_file_name }}"

libvirt_bridge_name: "br0"

### CONTROL vars
control_ign: "{{ ocp_install_dir }}/master.ign"
control_cpu: "4"
control_memory: "16384"
control_type: master

### WORKER vars
worker_count: "3"
worker_ign: "{{ ocp_install_dir }}/worker.ign"
worker_cpu: "20"
worker_memory: "81920"
worker_type: "worker"

## Base domain for the cluster
base_domain: arvhomelab.com

### OCS Install vars
ocs_install: True # Set to False if you will not be installing OCS
ocs_node_disk_size: "450" # Size in Gi

