platform: "hypershift"
cluster_type: kubevirt
ocp_version: "4.11"
hypershift_image: "quay.io/openshift/origin-hypershift"
infra_cluster_name: "ocp-infra1"
infra_cluster_base_domain: "arvhomelab.com"
infra_cluster_kubeconfig: "{{ kubeconfig_dir }}/{{ infra_cluster_name }}"
infra_cluster_tenant_namespace: "clusters-{{ ocp_cluster_name }}"

## Hypershift cluster vars
ocp_cluster_name: "ocp-hyper1"
base_domain: "apps.{{ infra_cluster_name }}.{{ infra_cluster_base_domain }}"
service_publishing_strategy: "NodePort"

cluster_kubeconfig: "{{ kubeconfig_dir }}/{{ ocp_cluster_name }}"
staging_dir: "{{ staging_base_dir }}/{{ ocp_cluster_name }}"
staging_backup_dir: "{{ staging_base_dir }}/{{ ocp_cluster_name }}/backup"
ocp_install_dir: "{{ staging_dir }}/ocp-install"

# OCP Vars
ocp_bin_version: "{{ ocp_version }}"
ocp_bin_channel: "fast"
rhcos_bin_qcow_url: "{{ rhcos_bin_release_url }}/{{ kubevirt_rhcos_bin_archive_name }}"
rhcos_bin_archive_name: "{{ kubevirt_rhcos_bin_archive_name }}"
rhcos_bin_file_name: "{{ kubevirt_rhcos_bin_file_name }}"
ocp_network_type: "OpenShiftSDN"

### WORKER vars
worker_count: "2"
worker_cpu: "6"
worker_memory: "16Gi"

# Kubevirt CSI Driver vars
kubevirt_csi_service_kubeconfig: "kubevirt-csi-service-kubeconfig"
kubevirt_csi_infra_cluster_sc: "ocs-storagecluster-cephfs"