---
- name: Apply LVM NS and OG yaml
  k8s:
    state: present
    definition: "{{ lookup('template', '01-lvm-ns-og.yaml') }}"

- name: sleep for 5 seconds
  wait_for:
    timeout: 5
  
- name: Apply LVM Subscription yaml
  k8s:
    state: present
    definition: "{{ lookup('template', '02-lvm-sub.yaml') }}"

- name: sleep for 20 seconds
  wait_for:
    timeout: 20

- name: Wait until LVM Operator installation has succeeded
  shell:
    cmd: "{{ oc_bin }} get csv $({{ oc_bin }} get subscriptions.operators.coreos.com lvms-operator -n openshift-storage -o=jsonpath='{.status.currentCSV}') -n openshift-storage -o=jsonpath='{.status.phase}'"
  register: result
  until: result.stdout == "Succeeded"
  retries: 100
  delay: 5

- set_fact:
    standard_disks: "{{ list | default([]) }}"
    fast_disks: "{{ list | default([]) }}"

- name: loop through nodes and add disks to a list
  vars:
    node: "{{ item }}"
  include_tasks: create-disk-list.yaml
  loop: "{{ groups['worker'] | list }}"

- name: Apply LVMCluster Instance yaml
  k8s:
    state: present
    definition: "{{ lookup('template', '03-lvm-cluster.yaml') }}"

- name: sleep for 30 seconds
  wait_for:
    timeout: 30

- name: Create immediate bounding storage classes
  k8s:
    state: present
    definition: "{{ lookup('template', '04-lvm-sc.yaml') }}"

- name: Wait until LVMCluster is ready
  shell:
    cmd: "{{ oc_bin }} get LVMCluster -n openshift-storage lvmcluster -o=jsonpath='{.status.state}'"
  register: result
  until: result.stdout == "Ready"
  retries: 100
  delay: 5
