apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  namespace: openshift-cnv
  name: kubevirt-hyperconverged
  annotations:
    deployOVS: 'false'
spec:
  liveMigrationConfig:
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  evictionStrategy: LiveMigrateIfPossible
  workloadUpdateStrategy:
    batchEvictionInterval: 1m0s
    batchEvictionSize: 10
    workloadUpdateMethods:
      - LiveMigrate
      - Evict
  featureGates:
    deployTektonTaskResources: false
    enableCommonBootImageImport: true
    withHostPassthroughCPU: false
    downwardMetrics: false
    disableMDevConfiguration: false
    enableApplicationAwareQuota: false
    deployKubeSecondaryDNS: false
    nonRoot: true
    alignCPUs: false
    enableManagedTenantQuota: false
    deployVmConsoleProxy: false
    persistentReservation: false
    autoResourceLimits: false
  uninstallStrategy: BlockUninstallIfWorkloadsExist
