# Run sample

# cd to ansible directory
# export VARSDIR=`pwd`/vars/hypershift
# sudo ansible-playbook playbooks/openshift-hypershift-cluster-deploy.yaml -e config=$VARSDIR/main.yaml -e config_dir=$VARSDIR
## If you are using a vault file in your vars use --vault-id @prompt 
# sudo ansible-playbook  playbooks/openshift-hypershift-cluster-deploy.yaml  --vault-password-file vaultpass -e config=$VARSDIR/main.yaml -e config_dir=$VARSDIR
# -e update_hypershift_cli=true      <- force rebuild of hypershift binary


- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - ansible-config-load
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost
  connection: local
  roles:
    - staging-dir-setup
  tags:
    - staging-dir-setup
    - pre-deploy


- name: Build Hyperhift Binary
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
  roles:
    - hypershift/hypershift-cli-build
  tags:
    - hypershift-cli-build


- name: Create Hypershift cluster
  hosts: localhost
  connection: local
  environment:
    KUBERNETES_MASTER: "{{ infra_cluster_kubeconfig }}"
    KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
  roles:
    - hypershift/hypershift-cluster-deploy
  tags:
    - hypershift-cluster-deploy


- name: Add HTPasswd auth provider
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ cluster_kubeconfig }}"
  roles:
    - openshift-auth-provider
  tags:
    - openshift-auth-provider
