# Run sample

# cd to ansible directory
# export VARSDIR=`pwd`/vars/hypershift
# ansible-playbook playbooks/openshift-hypershift-cluster-deploy.yaml -e config=$VARSDIR/main.yaml -e config_dir=$VARSDIR
# -e update_hypershift_cli=true      <- force rebuild of hypershift binary


- name: Include a play after another play
  import_playbook: openshift-hypershift-cluster-destroy.yaml

- name: Clear errors
  hosts:  all:localhost
  connection: local
  tasks:
    - meta: clear_host_errors

- name: Load cluster configs
  hosts: localhost:worker:control
  connection: local
  roles:
    - role: ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost
  connection: local
  roles:
    - staging-dir-setup
  tags:
    - always

- name: Get Infra cluster credentials
  hosts: localhost
  connection: local
  roles:
    - role: openshift-credentials-get
      vars:
        cluster: "{{ infra_cluster_name }}"
  tags:
    - always

- name: Load cluster configs
  hosts: localhost:all
  connection: local
  roles:
    - role: ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Get Hyperhift Binary
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
  roles:
    - hypershift/hypershift-cli-build
  tags:
    - hypershift-cli-build


- name: Create Hypershift cluster
  hosts: localhost
  connection: local
  environment:
    KUBERNETES_MASTER: "{{ infra_cluster_kubeconfig }}"
    KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
  roles:
    - hypershift/hypershift-cluster-deploy
  tags:
    - hypershift-cluster-deploy
