# Run sample

# cd to ansible directory
# ansible-playbook playbooks/openshift-O^3-cluster-destroy.yaml -i `pwd`/vars/tenant1/inventory -e config=`pwd`/vars/tenant1/main.yaml


- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - ansible-config-load
  tags:
    - always


- name: Destroy O^3 cluster
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
  roles:
    - ozone-destroy-cluster
  tags:
    - ozone-destroy-cluster

