# Run sample

# cd to ansible directory
# export CLUSTER_NAME=tenant1
# ansible-playbook playbooks/openshift-O^3-cluster-deploy.yaml -i ../ocp-cluster-vars/vars/$CLUSTER_NAME/inventory.yaml -e cluster_name=$CLUSTER_NAME --vault-password-file ./vault-password-file

#### Options
# --skip-tags pre-deploy
# --tags openshift-install-time-operations,openshift-auth-provider


# - name: Include a play after another play
#   import_playbook: openshift-O^3-cluster-destroy.yaml

# - name: Clear errors
#   hosts: all:localhost
#   connection: local
#   tasks:
#     - meta: clear_host_errors


- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - role: common/ansible-config-load
      action: base
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost:hypervisor:webserver
  roles:
    - common/staging-dir-setup
  tags:
    - always

- name: Get Infra cluster credentials
  hosts: localhost
  connection: local
  roles:
    - role: deploy/openshift-credentials-get
      vars:
        cluster: "{{ infra_cluster_fqdn }}"
  tags:
    - always

- name: Load cluster configs
  hosts: all:localhost
  connection: local
  roles:
    - role: common/ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Download Artifacts
  hosts: localhost
  roles:
    - deploy/openshift-download-artifacts
  tags:
    - openshift-download-artifacts
    - pre-deploy

- name: Create OpenShift manifest
  hosts: localhost
  connection: local
  roles:
    - deploy/openshift-create-manifest
  tags:
    - openshift-create-manifest

- name: Create OpenShift Agent ISO and stage it on webserver
  hosts: localhost
  roles:
    - deploy/openshift-agent-iso-create-and-stage
  tags:
    - openshift-agent-iso-create-and-stage



# - name: Creat OpenShift manifest
#   hosts: localhost
#   connection: local
#   roles:
#     - openshift-create-manifest
#   tags:
#     - openshift-create-manifest

# - name: Create OpenShift iginition
#   hosts: localhost
#   connection: local
#   roles:
#     - openshift-iginition-create
#   tags:
#     - openshift-iginition

# - name: Upload bootstrap ignition to webserver
#   hosts: localhost
#   roles:
#     - openshift-iginition-upload-to-webserver
#   tags:
#     - openshift-iginition
    
# - name: Overwrite bootstrap ignition with ignition pointer
#   hosts: localhost
#   connection: local
#   roles:
#     - openshift-iginition-update
#   tags:
#     - openshift-iginition

# - name: Setup Project on Infra OCP cluster for O^3 cluster
#   hosts: localhost
#   connection: local
#   environment:
#     KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
#   roles:
#     - ozone-setup-project-on-infra-ocp
#   tags:
#     - ozone-setup-project-on-infra-ocp

# - name: Deploy VMs for O^3 cluster nodes
#   hosts: bootstrap:control:worker
#   connection: local
#   gather_facts: false
#   environment:
#     KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
#   roles:
#     - ozone-deploy-vm
#   tags:
#     - ozone-deploy-vm
#     - deploy

# - name: OCP install time operations
#   hosts: localhost
#   connection: local
#   environment:
#     KUBECONFIG: "{{ cluster_kubeconfig }}"
#   roles:
#     - openshift-install-time-operations
#   tags:
#     - openshift-install-time-operations

# - name: Output kubeadmin password
#   hosts: localhost
#   connection: local
#   roles:
#     - openshift-show-admin-credentials
#   tags:
#     - openshift-show-admin-credentials

# - name: Add HTPasswd auth provider
#   hosts: localhost
#   connection: local
#   environment:
#     KUBECONFIG: "{{ cluster_kubeconfig }}"
#   roles:
#     - openshift-auth-provider
#   tags:
#     - openshift-auth-provider

