# Run sample

# cd to ansible directory
# export CLUSTER_NAME=libvirt-infra1
# ansible-playbook playbooks/openshift-libvirt-cluster-destroy.yaml -i ../ocp-cluster-vars/vars/$CLUSTER_NAME -e cluster_name=$CLUSTER_NAME --vault-password-file ./vault-password-file

#### Options
# --skip-tags pre-deploy
# --tags openshift-install-time-operations,openshift-auth-provider


- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - role: ansible-config-load
      action: base
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost:hypervisor
  connection: local
  roles:
    - staging-dir-setup
  tags:
    - always

- name: Load cluster configs
  hosts: localhost:worker:control:hypervisor:bootstrap
  connection: local
  roles:
    - role: ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Remove libvirt Cluster VMs
  hosts: hypervisor
  roles:
    - libvirt-remove-cluster
  tags:
    - libvirt-remove-cluster

- name: Clean Host Storage
  hosts: hypervisor
  roles:
    - libvirt-clean-host-storage
  tags:
    - libvirt-clean-host-storage


########### REMOVE ROLE
# - name: Clean data disks
#   hosts: hypervisor
#   connection: local
#   roles:
#     - role: openshift-clean-host-storage
#       when:
#         - data_storage is defined
#         - data_storage == True
#   tags:
#     - openshift-clean-host-storage

# - name: Remove cluster kubeconfig
#   hosts: localhost
#   connection: local
#   roles:
#     - openshift-remove-kubeconfig
#   tags:
#     - openshift-remove-kubeconfig
#     - cleanup

