# Run sample

# cd to ansible directory
# export VARSDIR=`pwd`/vars/libvirt
# sudo ansible-playbook playbooks/openshift-libvirt-cluster-destroy.yaml -i $VARSDIR/inventory -e config=$VARSDIR/main.yaml -e config_dir=$VARSDIR

#### Options
# --skip-tags pre-deploy
# --tags openshift-install-time-operations,openshift-auth-provider


- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - role: ansible-config-load
      action: base
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost
  connection: local
  roles:
    - staging-dir-setup
  tags:
    - always

- name: Load cluster configs
  hosts: localhost:worker:control
  connection: local
  roles:
    - role: ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Remove libvirt Cluster VMs
  hosts: all
  connection: local
  roles:
    - libvirt-remove-cluster
  tags:
    - libvirt-remove-cluster

- name: Clean Host Storage
  hosts: worker
  connection: local
  roles:
    - libvirt-clean-host-storage
  tags:
    - libvirt-clean-host-storage

- name: Clean data disks
  hosts: worker
  connection: local
  roles:
    - role: openshift-clean-host-storage
      when:
        - data_storage is defined
        - data_storage == True
  tags:
    - openshift-clean-host-storage


- name: Remove cluster kubeconfig
  hosts: localhost
  connection: local
  roles:
    - openshift-remove-kubeconfig
  tags:
    - openshift-remove-kubeconfig
    - cleanup

