##################################################################
## This playbook is not ready for use                           ##
##################################################################

# Run sample

# cd to ansible directory
# export CLUSTER_NAME=infra1.1
# ansible-playbook playbooks/openshift-kvm-vm-cluster-deco.yaml -i ../ocp-cluster-vars/vars/$CLUSTER_NAME/inventory.yaml -e cluster_name=$CLUSTER_NAME --vault-password-file ./vault-password-file

#### Options
# --skip-tags pre-deploy
# --tags openshift-install-time-operations,openshift-auth-provider

- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - role: common/ansible-config-load
      action: base
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost:hypervisor
  connection: local
  roles:
    - common/staging-dir-setup
  tags:
    - always

- name: Load cluster configs
  hosts: localhost:worker:control:hypervisor
  connection: local
  roles:
    - role: common/ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Remove KVM VMs
  hosts: control:worker
  gather_facts: False
  roles:
    - role: deco/kvm-remove-vms
      when: type == "kvm"
  tags:
    - kvm-remove-vms

- name: Remove VM base storage
  hosts: hypervisor
  roles:
    - deco/kvm-remove-storage
  tags:
    - kvm-remove-storage

- name: Remove additional VM storage and clean disks
  hosts: worker
  gather_facts: False
  roles:
    - role: deco/kvm-clean-host-storage
      when: type == "kvm"
  tags:
    - kvm-clean-host-storage

### placeholder for are metal deco steps (shutdown)
