# Run sample

# cd to ansible directory
# export VARSDIR=`pwd`/vars/hypershift
# sudo ansible-playbook playbooks/openshift-bm-test.yaml --vault-id @prompt -i $VARSDIR/inventory -e config=$VARSDIR/main.yaml -e config_dir=$VARSDIR
# sudo ansible-playbook playbooks/openshift-bm-test.yaml --vault-password-file vaultpass -e config=$VARSDIR/main.yaml -e config_dir=$VARSDIR -i $VARSDIR/inventory

- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - ansible-config-load
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost
  connection: local
  roles:
    - staging-dir-setup
  tags:
    - staging-dir-setup
    - pre-deploy

# Run Hypershift installer
- name: Test idrac access
  hosts: worker
  connection: local
  roles:
    - role: idrac-operations
      action: pxe-boot

