# Run sample

# cd to ansible directory
# export CLUSTER_NAME=ocp-tenant1
# ansible-playbook playbooks/openshift-O^3-cluster-deco.yaml -i ../ocp-cluster-vars/vars/$CLUSTER_NAME/inventory.yaml -e cluster_name=$CLUSTER_NAME --vault-password-file ./vault-password-file

- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - role: common/ansible-config-load
      action: base
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost:hypervisor:webserver
  roles:
    - common/staging-dir-setup
  tags:
    - always

- name: Get Infra cluster credentials
  hosts: localhost
  connection: local
  roles:
    - role: deploy/openshift-credentials-get
      vars:
        cluster: "{{ infra_cluster_fqdn }}"
  tags:
    - always

- name: Load cluster configs
  hosts: all:localhost
  connection: local
  roles:
    - role: common/ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Download Artifacts
  hosts: localhost
  roles:
    - deploy/openshift-download-artifacts
  tags:
    - openshift-download-artifacts
    - pre-deploy

- name: Destroy O^3 cluster
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
  roles:
    - deco/ozone-destroy-cluster
  tags:
    - ozone-destroy-cluster

# - name: Remove cluster kubeconfig
#   hosts: localhost
#   connection: local
#   roles:
#     - deco/openshift-remove-kubeconfig
#   tags:
#     - openshift-remove-kubeconfig
#     - cleanup