# Run sample

# cd to ansible directory
# export VARSDIR=`pwd`/vars/hypershift
# sudo ansible-playbook playbooks/openshift-hypershift-cluster-destroy.yaml -e config=$VARSDIR/main.yaml -e config_dir=$VARSDIR


- name: Load configs
  hosts: all:localhost
  connection: local
  roles:
    - role: ansible-config-load
      action: base
  tags:
    - always

- name: Setup Staging Directory
  hosts: localhost
  connection: local
  roles:
    - staging-dir-setup
  tags:
    - always

- name: Get Infra cluster credentials
  hosts: localhost
  connection: local
  roles:
    - role: openshift-credentials-get
      vars:
        cluster: "{{ infra_cluster_name }}"
  tags:
    - always

- name: Load cluster configs
  hosts: localhost:all
  connection: local
  roles:
    - role: ansible-config-load
      action: cluster-config
  tags:
    - always

- name: Build Hyperhift Binary
  hosts: localhost
  connection: local
  roles:
    - hypershift/hypershift-cli-build
  tags:
    - hypershift-cli-build

- name: Destroy Hypershift cluster
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ infra_cluster_kubeconfig }}"
    KUBERNETES_MASTER: "{{ infra_cluster_kubeconfig }}"
  roles:
    - hypershift/hypershift-cluster-destroy
  tags:
    - hypershift-cluster-destroy

- name: Remove cluster kubeconfig
  hosts: localhost
  connection: local
  roles:
    - openshift-remove-kubeconfig
  tags:
    - openshift-remove-kubeconfig
    - cleanup